/* Generated by Yosys 0.22 (git sha1 f109fa3d4c5, gcc 12.2.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* \amaranth.hierarchy  = "requant.cm_a" *)
(* generator = "Amaranth" *)
module cm_a(gain, re, im, re_overflow, im_overflow, rst, clk, complex_in);
  reg \$auto$verilog_backend.cc:2083:dump_module$1  = 0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  wire [17:0] \$1 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" *)
  wire \$11 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *)
  wire \$13 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" *)
  wire \$15 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *)
  wire \$17 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" *)
  wire \$19 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *)
  wire \$21 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" *)
  wire \$23 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:71" *)
  wire [28:0] \$3 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  wire [17:0] \$5 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:72" *)
  wire [28:0] \$7 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *)
  wire \$9 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:40" *)
  input [35:0] complex_in;
  wire [35:0] complex_in;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  input [10:0] gain;
  wire [10:0] gain;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:45" *)
  output [17:0] im;
  reg [17:0] im = 18'h00000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:45" *)
  reg [17:0] \im$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:51" *)
  reg [28:0] im_gain = 29'h00000000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:51" *)
  reg [28:0] \im_gain$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:47" *)
  output im_overflow;
  reg im_overflow = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:47" *)
  reg \im_overflow$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:44" *)
  output [17:0] re;
  reg [17:0] re = 18'h00000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:44" *)
  reg [17:0] \re$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:50" *)
  reg [28:0] re_gain = 29'h00000000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:50" *)
  reg [28:0] \re_gain$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:46" *)
  output re_overflow;
  reg re_overflow = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:46" *)
  reg \re_overflow$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:52" *)
  reg sync_buf = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:52" *)
  reg \sync_buf$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:42" *)
  wire sync_in;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:48" *)
  reg sync_out = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:48" *)
  reg \sync_out$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:11" *)
  wire [17:0] unpack_im;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:10" *)
  wire [17:0] unpack_re;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:9" *)
  wire [35:0] unpack_unpack_in;
  assign \$9  = $signed(im_gain) > (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *) $signed(29'h0001ffff);
  assign \$11  = $signed(im_gain) < (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" *) $signed(29'h1ffe0000);
  assign \$13  = $signed(im_gain) > (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *) $signed(29'h0001ffff);
  assign \$15  = $signed(im_gain) < (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" *) $signed(29'h1ffe0000);
  assign \$17  = $signed(re_gain) > (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *) $signed(29'h0001ffff);
  assign \$1  = + (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *) gain;
  assign \$19  = $signed(re_gain) < (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" *) $signed(29'h1ffe0000);
  assign \$21  = $signed(re_gain) > (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *) $signed(29'h0001ffff);
  assign \$23  = $signed(re_gain) < (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" *) $signed(29'h1ffe0000);
  always @(posedge clk)
    sync_buf <= \sync_buf$next ;
  always @(posedge clk)
    im_gain <= \im_gain$next ;
  always @(posedge clk)
    re_gain <= \re_gain$next ;
  always @(posedge clk)
    im_overflow <= \im_overflow$next ;
  always @(posedge clk)
    im <= \im$next ;
  always @(posedge clk)
    re_overflow <= \re_overflow$next ;
  always @(posedge clk)
    re <= \re$next ;
  always @(posedge clk)
    sync_out <= \sync_out$next ;
  assign \$3  = $signed(unpack_im) * (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:71" *) $signed(\$1 );
  assign \$5  = + (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *) gain;
  assign \$7  = $signed(unpack_re) * (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:72" *) $signed(\$5 );
  unpack unpack (
    .im(unpack_im),
    .re(unpack_re),
    .unpack_in(unpack_unpack_in)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \sync_buf$next  = 1'h0;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sync_buf$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \im_gain$next  = \$3 ;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \im_gain$next  = 29'h00000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \re_gain$next  = \$7 ;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \re_gain$next  = 29'h00000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *)
    casez ({ \$11 , \$9  })
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" */
      2'b?1:
          \im_overflow$next  = 1'h1;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" */
      2'b1?:
          \im_overflow$next  = 1'h1;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:88" */
      default:
          \im_overflow$next  = 1'h0;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \im_overflow$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *)
    casez ({ \$15 , \$13  })
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" */
      2'b?1:
          \im$next  = 18'h1ffff;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" */
      2'b1?:
          \im$next  = 18'h20000;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:88" */
      default:
          \im$next  = im_gain[17:0];
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \im$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *)
    casez ({ \$19 , \$17  })
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" */
      2'b?1:
          \re_overflow$next  = 1'h1;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" */
      2'b1?:
          \re_overflow$next  = 1'h1;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:98" */
      default:
          \re_overflow$next  = 1'h0;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \re_overflow$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *)
    casez ({ \$23 , \$21  })
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" */
      2'b?1:
          \re$next  = 18'h1ffff;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" */
      2'b1?:
          \re$next  = 18'h20000;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:98" */
      default:
          \re$next  = re_gain[17:0];
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \re$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \sync_out$next  = sync_buf;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sync_out$next  = 1'h0;
    endcase
  end
  assign sync_in = 1'h0;
  assign unpack_unpack_in = complex_in;
endmodule

(* \amaranth.hierarchy  = "requant.cm_b" *)
(* generator = "Amaranth" *)
module cm_b(gain, re, im, re_overflow, im_overflow, rst, clk, complex_in);
  reg \$auto$verilog_backend.cc:2083:dump_module$2  = 0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  wire [17:0] \$1 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" *)
  wire \$11 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *)
  wire \$13 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" *)
  wire \$15 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *)
  wire \$17 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" *)
  wire \$19 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *)
  wire \$21 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" *)
  wire \$23 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:71" *)
  wire [28:0] \$3 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  wire [17:0] \$5 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:72" *)
  wire [28:0] \$7 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *)
  wire \$9 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:40" *)
  input [35:0] complex_in;
  wire [35:0] complex_in;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  input [10:0] gain;
  wire [10:0] gain;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:45" *)
  output [17:0] im;
  reg [17:0] im = 18'h00000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:45" *)
  reg [17:0] \im$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:51" *)
  reg [28:0] im_gain = 29'h00000000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:51" *)
  reg [28:0] \im_gain$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:47" *)
  output im_overflow;
  reg im_overflow = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:47" *)
  reg \im_overflow$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:44" *)
  output [17:0] re;
  reg [17:0] re = 18'h00000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:44" *)
  reg [17:0] \re$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:50" *)
  reg [28:0] re_gain = 29'h00000000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:50" *)
  reg [28:0] \re_gain$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:46" *)
  output re_overflow;
  reg re_overflow = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:46" *)
  reg \re_overflow$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:52" *)
  reg sync_buf = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:52" *)
  reg \sync_buf$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:42" *)
  wire sync_in;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:48" *)
  reg sync_out = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:48" *)
  reg \sync_out$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:11" *)
  wire [17:0] unpack_im;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:10" *)
  wire [17:0] unpack_re;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:9" *)
  wire [35:0] unpack_unpack_in;
  assign \$9  = $signed(im_gain) > (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *) $signed(29'h0001ffff);
  assign \$11  = $signed(im_gain) < (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" *) $signed(29'h1ffe0000);
  assign \$13  = $signed(im_gain) > (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *) $signed(29'h0001ffff);
  assign \$15  = $signed(im_gain) < (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" *) $signed(29'h1ffe0000);
  assign \$17  = $signed(re_gain) > (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *) $signed(29'h0001ffff);
  assign \$1  = + (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *) gain;
  assign \$19  = $signed(re_gain) < (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" *) $signed(29'h1ffe0000);
  assign \$21  = $signed(re_gain) > (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *) $signed(29'h0001ffff);
  assign \$23  = $signed(re_gain) < (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" *) $signed(29'h1ffe0000);
  always @(posedge clk)
    sync_buf <= \sync_buf$next ;
  always @(posedge clk)
    im_gain <= \im_gain$next ;
  always @(posedge clk)
    re_gain <= \re_gain$next ;
  always @(posedge clk)
    im_overflow <= \im_overflow$next ;
  always @(posedge clk)
    im <= \im$next ;
  always @(posedge clk)
    re_overflow <= \re_overflow$next ;
  always @(posedge clk)
    re <= \re$next ;
  always @(posedge clk)
    sync_out <= \sync_out$next ;
  assign \$3  = $signed(unpack_im) * (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:71" *) $signed(\$1 );
  assign \$5  = + (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *) gain;
  assign \$7  = $signed(unpack_re) * (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:72" *) $signed(\$5 );
  \unpack$1  unpack (
    .im(unpack_im),
    .re(unpack_re),
    .unpack_in(unpack_unpack_in)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \sync_buf$next  = 1'h0;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sync_buf$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \im_gain$next  = \$3 ;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \im_gain$next  = 29'h00000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \re_gain$next  = \$7 ;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \re_gain$next  = 29'h00000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *)
    casez ({ \$11 , \$9  })
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" */
      2'b?1:
          \im_overflow$next  = 1'h1;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" */
      2'b1?:
          \im_overflow$next  = 1'h1;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:88" */
      default:
          \im_overflow$next  = 1'h0;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \im_overflow$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" *)
    casez ({ \$15 , \$13  })
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:82" */
      2'b?1:
          \im$next  = 18'h1ffff;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:85" */
      2'b1?:
          \im$next  = 18'h20000;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:88" */
      default:
          \im$next  = im_gain[17:0];
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \im$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *)
    casez ({ \$19 , \$17  })
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" */
      2'b?1:
          \re_overflow$next  = 1'h1;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" */
      2'b1?:
          \re_overflow$next  = 1'h1;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:98" */
      default:
          \re_overflow$next  = 1'h0;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \re_overflow$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" *)
    casez ({ \$23 , \$21  })
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:92" */
      2'b?1:
          \re$next  = 18'h1ffff;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:95" */
      2'b1?:
          \re$next  = 18'h20000;
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:98" */
      default:
          \re$next  = re_gain[17:0];
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \re$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \sync_out$next  = sync_buf;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sync_out$next  = 1'h0;
    endcase
  end
  assign sync_in = 1'h0;
  assign unpack_unpack_in = complex_in;
endmodule

(* \amaranth.hierarchy  = "requant" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module requant(pol_b_in, sync_in, gain, ce, pol_a_out, pol_b_out, sync_out, pol_a_overflow, pol_b_overflow, addr, clk, rst, pol_a_in);
  reg \$auto$verilog_backend.cc:2083:dump_module$3  = 0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:88" *)
  wire [11:0] \$1 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:96" *)
  wire \$10 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:103" *)
  wire \$12 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:88" *)
  wire [11:0] \$2 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:88" *)
  wire [11:0] \$4 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:88" *)
  wire [11:0] \$6 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/back/rtlil.py:569" *)
  wire \$7 ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:37" *)
  output [10:0] addr;
  reg [10:0] addr = 11'h000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:37" *)
  reg [10:0] \addr$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:27" *)
  input ce;
  wire ce;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:40" *)
  reg [35:0] cm_a_complex_in = 36'h000000000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:40" *)
  reg [35:0] \cm_a_complex_in$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  reg [10:0] cm_a_gain = 11'h000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  reg [10:0] \cm_a_gain$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:45" *)
  wire [17:0] cm_a_im;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:47" *)
  wire cm_a_im_overflow;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:44" *)
  wire [17:0] cm_a_re;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:46" *)
  wire cm_a_re_overflow;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:40" *)
  reg [35:0] cm_b_complex_in = 36'h000000000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:40" *)
  reg [35:0] \cm_b_complex_in$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  reg [10:0] cm_b_gain = 11'h000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:41" *)
  reg [10:0] \cm_b_gain$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:45" *)
  wire [17:0] cm_b_im;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:47" *)
  wire cm_b_im_overflow;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:44" *)
  wire [17:0] cm_b_re;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:46" *)
  wire cm_b_re_overflow;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:24" *)
  input [10:0] gain;
  wire [10:0] gain;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:41" *)
  reg [17:0] inter_im_a = 18'h00000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:41" *)
  reg [17:0] \inter_im_a$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:45" *)
  reg [17:0] inter_im_b = 18'h00000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:45" *)
  reg [17:0] \inter_im_b$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:42" *)
  reg inter_ovfl_a = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:42" *)
  reg \inter_ovfl_a$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:46" *)
  reg inter_ovfl_b = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:46" *)
  reg \inter_ovfl_b$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:40" *)
  reg [17:0] inter_re_a = 18'h00000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:40" *)
  reg [17:0] \inter_re_a$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:44" *)
  reg [17:0] inter_re_b = 18'h00000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:44" *)
  reg [17:0] \inter_re_b$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:22" *)
  input [35:0] pol_a_in;
  wire [35:0] pol_a_in;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:30" *)
  output [15:0] pol_a_out;
  reg [15:0] pol_a_out = 16'h0000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:30" *)
  reg [15:0] \pol_a_out$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:34" *)
  output pol_a_overflow;
  reg pol_a_overflow = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:34" *)
  reg \pol_a_overflow$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:23" *)
  input [35:0] pol_b_in;
  wire [35:0] pol_b_in;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:31" *)
  output [15:0] pol_b_out;
  reg [15:0] pol_b_out = 16'h0000;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:31" *)
  reg [15:0] \pol_b_out$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:35" *)
  output pol_b_overflow;
  reg pol_b_overflow = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:35" *)
  reg \pol_b_overflow$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:48" *)
  reg [3:0] sync_buf = 4'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:48" *)
  reg [3:0] \sync_buf$next ;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:26" *)
  input sync_in;
  wire sync_in;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:32" *)
  output sync_out;
  reg sync_out = 1'h0;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:32" *)
  reg \sync_out$next ;
  assign \$10  = cm_a_re_overflow | (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:96" *) cm_a_im_overflow;
  assign \$12  = cm_b_re_overflow | (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:103" *) cm_b_im_overflow;
  always @(posedge clk)
    addr <= \addr$next ;
  always @(posedge clk)
    cm_a_complex_in <= \cm_a_complex_in$next ;
  always @(posedge clk)
    cm_a_gain <= \cm_a_gain$next ;
  always @(posedge clk)
    inter_re_a <= \inter_re_a$next ;
  always @(posedge clk)
    inter_im_a <= \inter_im_a$next ;
  always @(posedge clk)
    inter_ovfl_a <= \inter_ovfl_a$next ;
  always @(posedge clk)
    cm_b_complex_in <= \cm_b_complex_in$next ;
  always @(posedge clk)
    cm_b_gain <= \cm_b_gain$next ;
  always @(posedge clk)
    inter_re_b <= \inter_re_b$next ;
  always @(posedge clk)
    inter_im_b <= \inter_im_b$next ;
  always @(posedge clk)
    inter_ovfl_b <= \inter_ovfl_b$next ;
  always @(posedge clk)
    pol_a_out <= \pol_a_out$next ;
  always @(posedge clk)
    pol_b_out <= \pol_b_out$next ;
  always @(posedge clk)
    pol_a_overflow <= \pol_a_overflow$next ;
  always @(posedge clk)
    pol_b_overflow <= \pol_b_overflow$next ;
  always @(posedge clk)
    sync_out <= \sync_out$next ;
  assign \$2  = addr + (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:88" *) 1'h1;
  always @(posedge clk)
    sync_buf <= \sync_buf$next ;
  assign \$4  = \$2  % (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:88" *) 12'h800;
  cm_a cm_a (
    .clk(clk),
    .complex_in(cm_a_complex_in),
    .gain(cm_a_gain),
    .im(cm_a_im),
    .im_overflow(cm_a_im_overflow),
    .re(cm_a_re),
    .re_overflow(cm_a_re_overflow),
    .rst(rst)
  );
  cm_b cm_b (
    .clk(clk),
    .complex_in(cm_b_complex_in),
    .gain(cm_b_gain),
    .im(cm_b_im),
    .im_overflow(cm_b_im_overflow),
    .re(cm_b_re),
    .re_overflow(cm_b_re_overflow),
    .rst(rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \addr$next  = addr;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:84" *)
          casez (sync_in)
            /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:84" */
            1'h1:
                \addr$next  = 11'h000;
            /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:86" */
            default:
                \addr$next  = \$6 [10:0];
          endcase
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \addr$next  = 11'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \cm_a_complex_in$next  = cm_a_complex_in;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \cm_a_complex_in$next  = pol_a_in;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \cm_a_complex_in$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \inter_ovfl_b$next  = inter_ovfl_b;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \inter_ovfl_b$next  = \$12 ;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \inter_ovfl_b$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \pol_a_out$next  = pol_a_out;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \pol_a_out$next  = { inter_re_a[17:10], inter_im_a[17:10] };
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pol_a_out$next  = 16'h0000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \pol_b_out$next  = pol_b_out;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \pol_b_out$next  = { inter_re_b[17:10], inter_im_b[17:10] };
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pol_b_out$next  = 16'h0000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \pol_a_overflow$next  = pol_a_overflow;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \pol_a_overflow$next  = inter_ovfl_a;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pol_a_overflow$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \pol_b_overflow$next  = pol_b_overflow;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \pol_b_overflow$next  = inter_ovfl_b;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pol_b_overflow$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \sync_out$next  = sync_out;
    \sync_buf$next  = sync_buf;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          { \sync_buf$next , \sync_out$next  } = { sync_in, sync_buf };
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
        begin
          \sync_out$next  = 1'h0;
          \sync_buf$next  = 4'h0;
        end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \cm_a_gain$next  = cm_a_gain;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \cm_a_gain$next  = gain;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \cm_a_gain$next  = 11'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \inter_re_a$next  = inter_re_a;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \inter_re_a$next  = cm_a_re;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \inter_re_a$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \inter_im_a$next  = inter_im_a;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \inter_im_a$next  = cm_a_im;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \inter_im_a$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \inter_ovfl_a$next  = inter_ovfl_a;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \inter_ovfl_a$next  = \$10 ;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \inter_ovfl_a$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \cm_b_complex_in$next  = cm_b_complex_in;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \cm_b_complex_in$next  = pol_b_in;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \cm_b_complex_in$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \cm_b_gain$next  = cm_b_gain;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \cm_b_gain$next  = gain;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \cm_b_gain$next  = 11'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \inter_re_b$next  = inter_re_b;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \inter_re_b$next  = cm_b_re;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \inter_re_b$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \inter_im_b$next  = inter_im_b;
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" *)
    casez (ce)
      /* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/requant.py:82" */
      1'h1:
          \inter_im_b$next  = cm_b_im;
    endcase
    (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/.venv/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \inter_im_b$next  = 18'h00000;
    endcase
  end
  assign \$1  = \$6 ;
  assign \$7  = 1'h0;
  assign \$6  = \$4 ;
endmodule

(* \amaranth.hierarchy  = "requant.cm_a.unpack" *)
(* generator = "Amaranth" *)
module unpack(im, re, unpack_in);
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:11" *)
  output [17:0] im;
  wire [17:0] im;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:10" *)
  output [17:0] re;
  wire [17:0] re;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:9" *)
  input [35:0] unpack_in;
  wire [35:0] unpack_in;
  assign re = unpack_in[35:18];
  assign im = unpack_in[17:0];
endmodule

(* \amaranth.hierarchy  = "requant.cm_b.unpack" *)
(* generator = "Amaranth" *)
module \unpack$1 (im, re, unpack_in);
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:11" *)
  output [17:0] im;
  wire [17:0] im;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:10" *)
  output [17:0] re;
  wire [17:0] re;
  (* src = "/home/kiran/Dropbox/Projects/Python/gateware/hdl/gateware/complex.py:9" *)
  input [35:0] unpack_in;
  wire [35:0] unpack_in;
  assign re = unpack_in[35:18];
  assign im = unpack_in[17:0];
endmodule
